# Configuration for quantizing MiniMax-M2.1 Experts-only with AWQ
# Usage: python scripts/do_oneshot.py --config configs/quantize_MiniMax-M2.1-Experts-only-AWQ.yaml

model:
  name: "<path-to>/MiniMax-M2.1-BF16"

quantization:
  recipe: "./recipes/recipe_Minimax-M2.1-Experts-only-AWQ.yaml"

calibration_set: "configs/calibration_sets/calibrate_software_engineer.yaml"
