calibration_set:
  max_seq_length: 8192
  shuffle: true
  seed: 42
  datasets:
    - dataset: neuralmagic/calibration
      subset: LLM
      split: train
      columns: ["messages"]
      formatter: chat_completion
      num_samples: 64
